apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-management
  template:
    metadata:
      labels:
        app: contact-management
    spec:
      containers:
      - name: contact-management
        image: haripriyayathirajula/contact-management-app:latest
        ports:
        - containerPort: 8080
