apiVersion: v1
kind: Service
metadata:
  name: contact-management-service
spec:
  type: NodePort
  selector:
    app: contact-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
